
version: '3.8'

services:
  poke_bot:
    restart: unless-stopped
    image: ghcr.io/ice2heart/poke_bot:latest
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    restart: unless-stopped
    image: mongo
    volumes:
      - dbdata6:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"

volumes:
  dbdata6: