
version: '3.8'

services:
  poke_bot:
    image: ghcr.io/ice2heart/poke_bot:latest
    environment:
      - MONGO_ADDRES=mongodb://mongodb:27017/
      - MONGO_DB_NAME=pokebot
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6: